server:
  port: 8080
spring:
  application:
    name: gm
  datasource:
    url: jdbc:mysql://192.168.1.204:3306/db_gm?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    
  security:
    user:
      name: root
      password: root